#!/bin/bash

commits=(`git log -1 --pretty=%s`)

for commit in "${commits[@]}"
do
 	if [ $commit == "--migrate-i-am-shure" ]; then
        
        php artisan migrate:refresh --seed;
        wait;
        y;
        wait;
        y;
        wait;
        y;
        wait;
        y;

    fi
done

