export const ADD_DRINK_TO_SAVED_DRINKS = 'Events//ADD_DRINK_TO_SAVED_DRINKS'
export const REMOVE_DRINK_FROM_SAVED_DRINKS = 'User//REMOVE_DRINK_FROM_SAVED_DRINKS'
export const SET_SELECTED_CATEGORY = 'Drinks//SET_SELECTED_CATEGORY'
